const deck = [
  { "numero": "A", "naipe": "Copas", "imagem": "https://deckofcardsapi.com/static/img/AC.png" },
  { "numero": "2", "naipe": "Copas", "imagem": "https://deckofcardsapi.com/static/img/2C.png" },
  { "numero": "3", "naipe": "Copas", "imagem": "https://deckofcardsapi.com/static/img/3C.png" },
  { "numero": "4", "naipe": "Copas", "imagem": "https://deckofcardsapi.com/static/img/4C.png" },
  { "numero": "5", "naipe": "Copas", "imagem": "https://deckofcardsapi.com/static/img/5C.png" },
  { "numero": "6", "naipe": "Copas", "imagem": "https://deckofcardsapi.com/static/img/6C.png" },
  { "numero": "7", "naipe": "Copas", "imagem": "https://deckofcardsapi.com/static/img/7C.png" },
  { "numero": "8", "naipe": "Copas", "imagem": "https://deckofcardsapi.com/static/img/8C.png" },
  { "numero": "9", "naipe": "Copas", "imagem": "https://deckofcardsapi.com/static/img/9C.png" },
  { "numero": "10", "naipe": "Copas", "imagem": "https://deckofcardsapi.com/static/img/0C.png" },
  { "numero": "J", "naipe": "Copas", "imagem": "https://deckofcardsapi.com/static/img/JC.png" },
  { "numero": "Q", "naipe": "Copas", "imagem": "https://deckofcardsapi.com/static/img/QC.png" },
  { "numero": "K", "naipe": "Copas", "imagem": "https://deckofcardsapi.com/static/img/KC.png" },

  { "numero": "A", "naipe": "Espadas", "imagem": "https://deckofcardsapi.com/static/img/AS.png" },
  { "numero": "2", "naipe": "Espadas", "imagem": "https://deckofcardsapi.com/static/img/2S.png" },
  { "numero": "3", "naipe": "Espadas", "imagem": "https://deckofcardsapi.com/static/img/3S.png" },
  { "numero": "4", "naipe": "Espadas", "imagem": "https://deckofcardsapi.com/static/img/4S.png" },
  { "numero": "5", "naipe": "Espadas", "imagem": "https://deckofcardsapi.com/static/img/5S.png" },
  { "numero": "6", "naipe": "Espadas", "imagem": "https://deckofcardsapi.com/static/img/6S.png" },
  { "numero": "7", "naipe": "Espadas", "imagem": "https://deckofcardsapi.com/static/img/7S.png" },
  { "numero": "8", "naipe": "Espadas", "imagem": "https://deckofcardsapi.com/static/img/8S.png" },
  { "numero": "9", "naipe": "Espadas", "imagem": "https://deckofcardsapi.com/static/img/9S.png" },
  { "numero": "10", "naipe": "Espadas", "imagem": "https://deckofcardsapi.com/static/img/0S.png" },
  { "numero": "J", "naipe": "Espadas", "imagem": "https://deckofcardsapi.com/static/img/JS.png" },
  { "numero": "Q", "naipe": "Espadas", "imagem": "https://deckofcardsapi.com/static/img/QS.png" },
  { "numero": "K", "naipe": "Espadas", "imagem": "https://deckofcardsapi.com/static/img/KS.png" },

  { "numero": "A", "naipe": "Ouros", "imagem": "https://deckofcardsapi.com/static/img/AD.png" },
  { "numero": "2", "naipe": "Ouros", "imagem": "https://deckofcardsapi.com/static/img/2D.png" },
  { "numero": "3", "naipe": "Ouros", "imagem": "https://deckofcardsapi.com/static/img/3D.png" },
  { "numero": "4", "naipe": "Ouros", "imagem": "https://deckofcardsapi.com/static/img/4D.png" },
  { "numero": "5", "naipe": "Ouros", "imagem": "https://deckofcardsapi.com/static/img/5D.png" },
  { "numero": "6", "naipe": "Ouros", "imagem": "https://deckofcardsapi.com/static/img/6D.png" },
  { "numero": "7", "naipe": "Ouros", "imagem": "https://deckofcardsapi.com/static/img/7D.png" },
  { "numero": "8", "naipe": "Ouros", "imagem": "https://deckofcardsapi.com/static/img/8D.png" },
  { "numero": "9", "naipe": "Ouros", "imagem": "https://deckofcardsapi.com/static/img/9D.png" },
  { "numero": "10", "naipe": "Ouros", "imagem": "https://deckofcardsapi.com/static/img/0D.png" },
  { "numero": "J", "naipe": "Ouros", "imagem": "https://deckofcardsapi.com/static/img/JD.png" },
  { "numero": "Q", "naipe": "Ouros", "imagem": "https://deckofcardsapi.com/static/img/QD.png" },
  { "numero": "K", "naipe": "Ouros", "imagem": "https://deckofcardsapi.com/static/img/KD.png" },

  { "numero": "A", "naipe": "Paus", "imagem": "https://deckofcardsapi.com/static/img/AH.png" },
  { "numero": "2", "naipe": "Paus", "imagem": "https://deckofcardsapi.com/static/img/2H.png" },
  { "numero": "3", "naipe": "Paus", "imagem": "https://deckofcardsapi.com/static/img/3H.png" },
  { "numero": "4", "naipe": "Paus", "imagem": "https://deckofcardsapi.com/static/img/4H.png" },
  { "numero": "5", "naipe": "Paus", "imagem": "https://deckofcardsapi.com/static/img/5H.png" },
  { "numero": "6", "naipe": "Paus", "imagem": "https://deckofcardsapi.com/static/img/6H.png" },
  { "numero": "7", "naipe": "Paus", "imagem": "https://deckofcardsapi.com/static/img/7H.png" },
  { "numero": "8", "naipe": "Paus", "imagem": "https://deckofcardsapi.com/static/img/8H.png" },
  { "numero": "9", "naipe": "Paus", "imagem": "https://deckofcardsapi.com/static/img/9H.png" },
  { "numero": "10", "naipe": "Paus", "imagem": "https://deckofcardsapi.com/static/img/0H.png" },
  { "numero": "J", "naipe": "Paus", "imagem": "https://deckofcardsapi.com/static/img/JH.png" },
  { "numero": "Q", "naipe": "Paus", "imagem": "https://deckofcardsapi.com/static/img/QH.png" },
  { "numero": "K", "naipe": "Paus", "imagem": "https://deckofcardsapi.com/static/img/KH.png" }
]


export default deck;